/* Tema II, IPO2627.pdf, páginas 49–115. Los casos trasladan conceptos a decisiones de diseño.
   La primera opción de cada pregunta es la correcta; test.js baraja las cuatro opciones. */
const BLOQUES = ['Modelos mentales', 'Procesamiento y sentidos', 'Percepción visual y atención', 'Memoria sensorial y de trabajo', 'Memoria a largo plazo y casos'];
const BANCO = [
  [0,52,'Un usuario recuerda cómo funciona una aplicación relacionando sus funciones entre sí. ¿Qué idea del tema explica mejor esta organización?',[
    ['El conocimiento se organiza en estructuras semánticas; los modelos mentales son especialmente relevantes para IPO.','La página 52 rechaza una memoria organizada caóticamente.'],['La información permanece aislada en la memoria sensorial.','La memoria sensorial retiene estímulos brevemente, no organiza conocimiento del sistema.'],['Solo puede aprenderse una interfaz memorizando cada pantalla por separado.','Las relaciones semánticas facilitan adquisición y recuperación.'],['El modelo mental es el código interno de la aplicación.','Es una representación que tiene la persona, no la implementación.']]],
  [0,53,'Alguien aprende a usar un editor con práctica y formación. ¿Cómo se forma su modelo mental según Norman?',[
    ['Mediante experiencia, entrenamiento y aprendizaje.','Las tres vías aparecen en la página 53.'],['Solo mediante instrucciones escritas antes del primer uso.','El tema también incluye experiencia y entrenamiento.'],['Nace completo y no cambia con el uso.','Los modelos mentales se forman y pueden cambiar.'],['Es una copia exacta del funcionamiento interno del editor.','Puede ser parcial e incluso inconsistente.']]],
  [0,54,'Un usuario sabe encender un ventilador, pero no entiende su mecanismo interno. ¿Qué característica ilustra?',[
    ['Un modelo mental parcial.','Se conoce lo suficiente para operar, sin comprender completamente el sistema.'],['Un modelo mental necesariamente acientífico.','Ignorar detalles no demuestra superstición.'],['Una inconsistencia lógica entre dos creencias.','No se describen creencias incompatibles.'],['La ausencia total de modelo mental.','La persona sí dispone de alguna representación operativa.']]],
  [0,54,'Tras actualizar una app de mapas, una persona reajusta lo que espera de su navegación. ¿Qué rasgo se pone de manifiesto?',[
    ['Los modelos mentales son inestables y pueden cambiar.','La app de mapas ilustra este rasgo en la página 54.'],['Todo cambio demuestra que antes no había modelo mental.','Un modelo anterior puede revisarse.'],['La memoria sensorial conserva para siempre el mapa anterior.','La memoria sensorial es transitoria.'],['Los modelos mentales siempre son completos.','Cambiar no prueba completitud.']]],
  [0,54,'Una persona cree simultáneamente dos explicaciones incompatibles sobre dónde están sus archivos. ¿Cuál es el diagnóstico más específico?',[
    ['Su modelo mental puede ser inconsistente.','Las creencias incompatibles ilustran la inconsistencia.'],['Su modelo mental es solamente parcial.','Parcialidad significa conocimiento incompleto, no necesariamente contradictorio.'],['Ha perdido la capacidad de percibir profundidad.','No se trata de visión espacial.'],['La interfaz tiene necesariamente un problema de brillo.','El caso no aporta evidencia sobre luminancia.']]],
  [0,55,'El icono de carrito lleva directamente al cobro, pero el usuario esperaba revisar artículos antes. ¿Por qué aparece el error?',[
    ['La operación difiere del modelo mental del usuario.','El PDF propone una página intermedia de resumen.'],['El usuario no tiene ningún modelo mental al pulsar.','Su expectativa sobre el carrito revela uno.'],['La memoria ecoica de la persona dura demasiado.','No hay un problema auditivo.'],['El problema se resuelve solo aumentando la velocidad del pago.','La discrepancia es conceptual, no de tiempo de respuesta.']]],
  [0,55,'Una interfaz cambia el significado habitual de un icono sin dar pistas. ¿Qué intervención favorece un modelo mental correcto?',[
    ['Respetar las convenciones o hacer explícita la nueva operación.','El tema destaca que el diseño debe ayudar a formar un modelo correcto, por ejemplo respetando convenciones.'],['Ocultar el resultado hasta que termine la tarea.','Impide contrastar la expectativa con la operación.'],['Suponer que todo modelo mental es preciso por definición.','Pueden ser parciales, inestables e inconsistentes.'],['Sustituir todas las etiquetas por colores.','El color no asegura comprensión de la operación.']]],
  [0,54,'Un equipo interpreta una creencia errónea de usuarios como un defecto moral y no investiga cómo entienden el producto. ¿Qué pierde?',[
    ['La oportunidad de conceptualizar sus conocimientos y construir una interacción apropiada.','La página 54 propone estudiar los modelos mentales del usuario.'],['La posibilidad de medir solo la frecuencia del procesador.','No aborda las expectativas del usuario.'],['La garantía de que todos comparten un modelo único.','El tema no afirma uniformidad entre personas.'],['La necesidad de analizar exclusivamente la retina.','El problema planteado es conceptual.']]],

  [1,60,'Un diseñador quiere saber cómo se percibe, almacena y recupera información al usar una web. ¿Qué disciplina aporta el modelo citado?',[
    ['La psicología cognitiva.','Estudia el procesamiento humano de información, incluida percepción, almacenamiento y recuperación.'],['La programación de dispositivos, por sí sola.','No explica esos procesos humanos.'],['Solo la óptica geométrica.','No cubre almacenamiento ni recuperación.'],['La fisiología muscular exclusivamente.','El problema también implica procesos cognitivos.']]],
  [1,61,'En el esquema de procesamiento, una alerta en pantalla llega a una persona. ¿Qué recorrido inicial es coherente?',[
    ['Salida del ordenador, sensores, memoria sensorial y atención hacia memoria de trabajo.','Es la dirección de entrada humana del esquema de la página 61.'],['Entrada del ordenador, efectores y memoria a largo plazo directamente.','Los efectores son el canal de acción, no de recepción.'],['Memoria a largo plazo del ordenador antes de los sensores.','El diagrama modela memoria humana y recepción sensorial.'],['Sistema vocal del usuario antes de percibir la pantalla.','La vocalización sería una posible acción posterior.']]],
  [1,63,'Una persona escucha una instrucción y responde en voz alta. ¿Qué par de canales describe el proceso?',[
    ['Oído como sensor y sistema vocal como efector.','El primero recibe; el segundo ejecuta la acción.'],['Oído como efector y sistema vocal como sensor.','Invierte las funciones.'],['Ambos como memorias sensoriales.','La voz es un canal de acción.'],['Retina como sensor y dedos como efectores obligatorios.','No corresponden al caso narrado.']]],
  [1,81,'Un menú telefónico transmite información mediante sonido. ¿Qué característica NO permite identificar por sí sola de dónde procede un sonido?',[
    ['Su asociación con una palabra escrita en pantalla.','La localización auditiva se basa en diferencias de tiempo e intensidad entre ambos oídos.'],['La diferencia de tiempo de llegada a cada oído.','Es una pista de posición expresamente mencionada.'],['La diferencia de intensidad percibida por ambos oídos.','También contribuye a localizarlo.'],['La comparación de lo que percibe el oído izquierdo y el derecho.','Es la base de las dos pistas citadas.']]],
  [1,82,'Un botón virtual da una pequeña vibración tras pulsarlo. ¿Qué aporta el canal háptico?',[
    ['Realimentación de la acción, útil también cuando no se depende de la vista.','El tema cita pulsar botones o teclas y su utilidad para algunas discapacidades.'],['Una prueba de que la pantalla ya no contiene información visual.','La vibración puede complementar la imagen.'],['Una sustitución obligatoria del sonido en toda interfaz.','No se establece esa exclusividad.'],['Una memoria a largo plazo de las pulsaciones.','La respuesta táctil no es un almacén de recuerdos.']]],
  [1,83,'Un mando aplica presión sobre las yemas de los dedos. ¿Qué receptor y zona son los más pertinentes?',[
    ['Mecanorreceptores; los dedos son especialmente sensibles.','La página 83 vincula mecanorreceptores con presión y destaca los dedos.'],['Termorreceptores; solo la espalda percibe tacto.','Termorreceptores responden al calor y el tacto se recibe por la piel.'],['Nocirreceptores; exclusivamente la retina.','No corresponde a presión ni a la zona indicada.'],['Memoria ecoica; las palmas.','La memoria ecoica es auditiva, no un receptor de presión.']]],
  [1,84,'Una experiencia de realidad virtual causa mareo al mover la cabeza. ¿Qué aspectos conviene revisar además del tacto cutáneo?',[
    ['La posición corporal cenestésica y la orientación, movimiento y aceleración vestibulares.','Desajustes de estos sentidos pueden causar mareo y desorientación.'],['Solo la elección de palabras del botón de salir.','No aborda la percepción del movimiento.'],['Solo la memoria declarativa semántica.','La página 84 atribuye estos riesgos a señales corporales.'],['La clasificación de los conos de color exclusivamente.','No basta para explicar el mareo descrito.']]],
  [1,85,'Una interfaz intenta comunicar estados con olores sostenidos durante minutos. ¿Qué limitación específica advierte el tema?',[
    ['La sensibilidad disminuye con el tiempo de exposición y varía entre personas.','Ambas dificultades figuran en la página 85.'],['Los olores no tienen relación posible con emociones.','El tema destaca esa conexión.'],['El olfato solo puede funcionar como efector.','Es un sentido, es decir, un canal de entrada.'],['Toda persona percibe un mismo olor con igual intensidad indefinidamente.','Contradice variación y adaptación sensorial.']]],

  [2,67,'Una interfaz depende de reconocer colores de noche y de distinguir formas sin suficiente luz. ¿Qué asociación de receptores es correcta?',[
    ['Conos para color; bastones para formas y visión nocturna.','La página 67 distingue ambas funciones.'],['Bastones para color; conos exclusivamente para audio.','Invierte la función de los bastones y atribuye audio a receptores visuales.'],['Conos únicamente para profundidad; bastones para olor.','No corresponde al texto.'],['Ambos son memorias que almacenan la pantalla.','Son receptores de la retina.']]],
  [2,68,'Se dibujan separadores finísimos que solo se distinguen del fondo por la componente azul. ¿Qué riesgo predice el tema?',[
    ['Bordes poco claros y elementos azules pequeños difíciles de enfocar.','Son consecuencias indicadas para diferencias basadas en azul.'],['Bordes más nítidos por la sensibilidad máxima al azul.','El ojo es menos sensible a longitudes cortas.'],['Mejora asegurada de lectura en la visión frontal.','Las líneas azules delgadas tienden a verse borrosas.'],['Desaparición de toda percepción de amarillo.','No se deriva de esa elección.']]],
  [2,70,'Se eligen letras azules sobre fondo amarillo para maximizar contraste. ¿Qué objeción recoge el PDF?',[
    ['Es una combinación oponente que puede dificultar ver las letras.','La página 70 da precisamente ese ejemplo.'],['Es la única combinación que el tema exige para texto.','Se recomienda evitar combinaciones oponentes.'],['El problema solo aparece si el texto está en rojo sobre blanco.','No es la combinación ejemplificada.'],['Los colores oponentes siempre mejoran los bordes.','El tema advierte de problemas perceptivos.']]],
  [2,72,'Un formulario señala los errores únicamente en rojo y los aciertos únicamente en verde. ¿Qué rediseño es más prudente?',[
    ['Añadir texto o símbolos que permitan distinguir el estado sin depender solo del color.','La página 72 advierte de problemas frecuentes de visión del color.'],['Quitar toda etiqueta y usar más tonos rojo-verde.','Aumenta la dependencia de la distinción problemática.'],['Suponer que la visión del color es idéntica para todas las personas.','El tema presenta distintas alteraciones.'],['Sustituirlo siempre por olor como único canal.','El olfato también tiene límites y no resuelve por sí solo el problema.']]],
  [2,73,'Una pantalla brillante provoca reflejos en una sala iluminada. ¿Cuál es el análisis apropiado?',[
    ['La luminancia y las fuentes de luz del entorno afectan a la percepción; conviene revisar su disposición.','La página 73 considera expresamente el ambiente luminoso y los destellos.'],['Solo importa el valor RGB de los iconos, nunca el entorno.','El ambiente altera la información percibida.'],['La agudeza mejora ilimitadamente aumentando la luminancia.','Una luminancia muy elevada incrementa el parpadeo.'],['El problema demuestra que los usuarios carecen de memoria sensorial.','Los reflejos no permiten esa conclusión.']]],
  [2,74,'En una escena 3D, un objeto tapa parte de otro y parece estar delante. ¿Qué clase de clave de profundidad interviene?',[
    ['Superposición, una clave dada por la imagen.','La superposición está en la lista de claves de imagen.'],['Disparidad binocular, exclusivamente.','Esta depende de la diferencia entre ojos, no del solapamiento descrito.'],['Paralaje de movimiento, exclusivamente.','Requiere cambio relativo al moverse, no solo solapamiento.'],['Memoria ecoica.','Es auditiva y no es una clave de profundidad visual.']]],
  [2,75,'Dos controles miden lo mismo en píxeles, pero uno se observa desde más lejos. ¿Qué inferencia es válida?',[
    ['Su ángulo visual puede diferir; tamaño y distancia condicionan la percepción del detalle.','Las páginas 75–76 relacionan el ángulo visual con ambos factores.'],['Tienen necesariamente idéntico ángulo visual.','La distancia cambia el ángulo aun con igual tamaño.'],['El más lejano siempre tiene un ángulo mayor.','A igual tamaño, alejarlo reduce el ángulo.'],['La separación percibida no depende de ningún umbral.','Se indican umbrales mínimos para detalles y espacios.']]],
  [2,77,'Una portada llena de avisos brillantes oculta la tarea que busca el visitante. ¿Qué explica mejor el problema?',[
    ['La atención filtra información limitada y depende de estímulos y objetivos del usuario.','El usuario no procesa toda la página; lo llamativo puede competir con zonas informativas.'],['El usuario analiza siempre cada píxel por igual.','El tema indica que selecciona zonas de alto contenido informativo.'],['Una imagen llamativa garantiza atención útil por la ceguera al banner.','La ceguera al banner es precisamente una advertencia.'],['Solo la memoria procedimental determina lo que entra por la retina.','La página 77 describe atención y percepción.']]],

  [3,90,'Un destello desaparece antes de que la persona pueda analizarlo. ¿Qué papel cumple la memoria sensorial?',[
    ['Retener brevemente el estímulo para posibilitar su transferencia a memoria de trabajo.','Funciona como buffer de corta duración.'],['Guardar para siempre el destello como conocimiento semántico.','Su almacenamiento dura muy poco.'],['Ejecutar la respuesta muscular sin atención.','No es un efector.'],['Eliminar la necesidad de interpretar cualquier estímulo.','Retener no equivale a comprender.']]],
  [3,91,'Una animación parece continua aunque se componga de cambios visuales breves. ¿Qué almacén está implicado más directamente?',[
    ['Memoria icónica, ligada al canal visual.','La persistencia visual aparece en las páginas 91–92.'],['Memoria ecoica, ligada al sonido.','No se describe un estímulo auditivo.'],['Memoria episódica de ayer.','No explica la persistencia visual inmediata.'],['Memoria procedimental condición-acción.','Se refiere a reglas para tareas.']]],
  [3,93,'Un teclado virtual emite un clic que confirma una pulsación mientras se mira otra zona. ¿Qué ejemplo del tema reproduce?',[
    ['Realimentación auditiva vinculada a la memoria ecoica.','La página 93 ofrece este ejemplo de confirmación.'],['Una clave de perspectiva lineal.','No hay percepción de profundidad visual.'],['Una prueba de que la memoria sensorial solo es visual.','El caso usa el canal auditivo.'],['Un recuerdo episódico de larga duración.','El clic confirma una acción presente.']]],
  [3,94,'En una fiesta se sigue una conversación entre varias. ¿Qué proceso explica la selección?',[
    ['Atención selectiva ante una capacidad limitada para retener información sensorial.','Es el ejemplo de la página 94.'],['Almacenamiento automático y completo de todas las conversaciones en memoria de trabajo.','La capacidad es limitada.'],['Ausencia de estímulos de los demás interlocutores.','Los estímulos existen aunque no se atiendan.'],['Acción de los efectores en lugar de percepción.','El ejemplo trata de selección de entrada.']]],
  [3,96,'Al hacer mentalmente una suma, la persona mantiene y manipula números mientras atiende a ellos. ¿Qué memoria usa?',[
    ['Memoria de trabajo.','Contiene símbolos activos manipulables mediante control voluntario.'],['Solo memoria icónica.','La memoria icónica es un buffer visual breve, no explica por sí sola la operación.'],['Solo memoria episódica.','Se refiere a acontecimientos vividos.'],['Exclusivamente receptores táctiles.','No son almacenes de símbolos.']]],
  [3,100,'Una secuencia larga se recuerda mejor agrupándola en unidades significativas. ¿Qué precisión evita malinterpretar el 7±2?',[
    ['Se refiere a unidades de información, que pueden ser asociaciones de elementos.','La agrupación puede aumentar cuántos elementos individuales caben en las unidades.'],['Garantiza recordar exactamente siete dígitos aislados a toda persona.','Es una estimación con variación y admite agrupaciones.'],['Significa que la memoria a largo plazo tiene solo siete recuerdos.','Se habla de capacidad limitada de trabajo.'],['La asociación impide formar huellas de memoria.','El tema indica lo contrario cuando la asociación tiene éxito.']]],
  [3,104,'Un cajero entrega dinero antes de devolver la tarjeta y la persona se marcha sin ella. ¿Qué modificación sigue el análisis de la página 104?',[
    ['Devolver la tarjeta antes del dinero.','Evita cerrar prematuramente la asociación de tarea terminada.'],['Entregar la tarjeta aún más tarde.','Aumenta el riesgo de olvido descrito.'],['Añadir música hablada y mantener el orden.','Puede introducir interferencia verbal, sin resolver la secuencia.'],['Ocultar la tarjeta durante toda la operación.','No garantiza su recuperación.']]],
  [3,107,'Una página exige leer resultados mientras suena una canción con letra que el usuario no atiende. ¿Qué efecto es plausible según el experimento citado?',[
    ['El habla de fondo puede interferir en el trabajo con información verbal incluso sin atención consciente.','Salamé y Baddeley distinguen texto hablado de ruido.'],['Solo interfiere si el usuario decide memorizar la canción.','El efecto se observó sin prestarle atención.'],['Un ruido no verbal produce necesariamente el mismo efecto observado.','En el experimento citado, el ruido no produjo ese efecto.'],['La letra mejora siempre las búsquedas verbales.','La aplicación al diseño advierte lo contrario.']]],

  [4,109,'Un equipo equipara memoria a largo plazo y memoria de trabajo porque ambas almacenan información. ¿Qué distinción ofrece el tema?',[
    ['La MLP tiene gran capacidad y pérdidas más lentas, aunque su acceso es más lento.','Contrasta con el acceso rápido y baja capacidad de trabajo.'],['La MLP es el buffer visual de milisegundos.','Eso corresponde a memoria sensorial icónica.'],['La memoria de trabajo tiene capacidad casi ilimitada.','La página 97 la describe como limitada.'],['La MLP no puede contener conocimientos adquiridos.','Almacena nuestro conocimiento.']]],
  [4,110,'Al recordar cómo actuar si aparece cierta señal, se recupera una regla condición-acción. ¿Qué tipo de memoria describe?',[
    ['Procedimental.','Guarda reglas de actuación y estrategias para tareas concretas.'],['Episódica.','Recoge eventos y experiencias personales seriadas.'],['Icónica.','Retiene brevemente información visual.'],['Ecoica.','Retiene brevemente información auditiva.']]],
  [4,110,'Una persona relata el encuentro que tuvo ayer y después enuncia una regla general sobre desconocidos. ¿Qué clasificación corresponde respectivamente?',[
    ['Episódica y semántica, ambas declarativas.','El episodio vivido y el conocimiento general se distinguen así en la página 110.'],['Procedimental y ecoica.','Ni el relato es una regla de actuación ni la generalización un eco breve.'],['Semántica y episódica.','Invierte el acontecimiento particular y el concepto general.'],['Icónica y memoria de trabajo, necesariamente.','No son las categorías de MLP ilustradas.']]],
  [4,112,'Para memorizar un concepto se distribuyen repasos durante varios días en vez de concentrarlos de una vez. ¿Qué hipótesis respalda la elección?',[
    ['Tiempo distribuido: aprender es más efectivo cuando el estudio se reparte en el tiempo.','Es una técnica de memorización descrita en la página 112.'],['Tiempo total: solo importa la posición del monitor.','La hipótesis de tiempo total relaciona cantidad aprendida y tiempo dedicado.'],['Primacía: toda sesión debe acabar con el primer elemento.','Primacía se refiere al recuerdo de posiciones en listas.'],['Paralaje: lo cercano cambia más rápido.','Es una pista de profundidad, no de estudio.']]],
  [4,113,'Después de aprender un nuevo teléfono cuesta recuperar el anterior. ¿Qué explicación aparece expresamente en el tema?',[
    ['La información nueva puede interferir con la antigua.','La página 113 da el nuevo número de teléfono como ejemplo de pérdida por interferencia.'],['La memoria sensorial visual conserva todos los teléfonos para siempre.','La memoria sensorial es muy breve.'],['Es prueba definitiva de destrucción física del recuerdo anterior.','El texto dice que no está claro si se olvida o cuesta recordar.'],['Solo se explica por un cambio en el ángulo visual.','No se describe un problema perceptivo.']]],
  [4,114,'Un usuario no puede decir de memoria el nombre de una herramienta, pero la identifica al verla entre opciones. ¿Qué distinción ilustra?',[
    ['Reconocimiento con pistas frente a recuerdo por reproducción; reconocer es menos complejo.','La presentación de la información facilita reconocerla.'],['Recuerdo con pistas frente a reconocimiento sin estímulos.','Invierte las definiciones.'],['Memoria de trabajo frente a bastones retinianos.','No distingue las dos formas de recuperación.'],['Olvido demostrado e irreversible.','Identificarla muestra que aún puede recuperarla con pistas.']]],
  [4,79,'Una imagen es un enlace, pero nada en su presentación sugiere que pueda pulsarse. ¿Qué falla más directamente?',[
    ['La capacidad percibida de ser presionada: visibilidad, forma funcional o acción coherente.','La página 79 usa el enlace oculto en imagen como ejemplo negativo de affordance.'],['La velocidad de lectura en palabras por minuto.','El problema es descubrir la función del objeto.'],['La clasificación de recuerdos episódicos.','No explica la acción que parece posible.'],['El paralaje de movimiento.','No se describe una escena 3D en movimiento.']]],
  [4,106,'Una interfaz obliga a repetir palabras mientras se recuerdan dígitos; otra combina repetir palabras con recordar movimientos. ¿Qué comparación respalda el tema?',[
    ['La primera combinación puede perjudicar más al compartir un almacén secundario.','La página 106 contrapone tareas que comparten almacén y tareas en almacenes distintos.'],['La segunda debe perjudicar siempre más porque usa dos modalidades.','El resultado expuesto es el contrario en esos ejemplos.'],['Ambas rinden necesariamente igual para toda persona.','El experimento registra diferencias según almacenes implicados.'],['Ninguna se relaciona con los límites de memoria de trabajo.','La página 106 trata precisamente de multitarea y memoria de trabajo.']]]
].map((q,i)=>({id:i+1,bloque:q[0],pagina:q[1],enunciado:q[2],opciones:q[3].map((o,j)=>({texto:o[0],explicacion:o[1],correcta:j===0}))}));
