/* Tema III, IPO2627.pdf, páginas 116–166. Los casos trasladan conceptos a decisiones de diseño.
   La primera opción de cada pregunta es la correcta; test.js baraja las cuatro opciones. */
const BLOQUES = ['Fundamentos y metáforas verbales', 'Metáforas visuales y globales', 'Metáfora del escritorio', 'Metodología de creación', 'Diseño y ejemplos'];
const BANCO = [
  [0,119,'Un equipo debe presentar una función abstracta a personas sin experiencia técnica. ¿Qué uso de las metáforas coincide con el tema?',[
    ['Comunicar el concepto de una forma familiar y accesible.','La página 119 atribuye precisamente esa función a las metáforas.'],['Reproducir todos los detalles internos del programa.','La metáfora facilita la comprensión, pero no tiene que copiar la implementación.'],['Sustituir el análisis de usuarios por una imagen decorativa.','La apariencia por sí sola no garantiza una comparación comprensible.'],['Obligar al usuario a aprender primero el dominio técnico.','La metáfora parte del conocimiento previo para acercar el dominio nuevo.']]],
  [0,121,'¿Qué condición convierte el uso de una palabra en una metáfora verbal, según la definición del tema?',[
    ['Usarla en un sentido distinto del habitual manteniendo una relación de analogía o semejanza.','Es la definición ofrecida en la página 121.'],['Usarla con exactamente el mismo significado y sin trasladar relaciones.','Sin cambio de sentido ni analogía no se produce la metáfora descrita.'],['Representarla necesariamente mediante un icono animado.','Eso añadiría una representación visual, pero no define la metáfora verbal.'],['Elegir una palabra desconocida para impedir asociaciones previas.','La utilidad de la metáfora depende precisamente de aprovechar asociaciones conocidas.']]],
  [0,121,'Una aplicación indica que el usuario puede “ahorrar”, “gastar” o “desaprovechar” tiempo. ¿Qué transferencia realiza?',[
    ['Trata el tiempo, que es abstracto, mediante expresiones asociadas al dinero.','Es uno de los ejemplos de metáfora verbal de la página 121.'],['Convierte literalmente los minutos en monedas canjeables.','La relación es lingüística y conceptual, no una transformación física.'],['Usa una metáfora global de oficina completa.','Las palabras citadas forman una comparación verbal, no el marco de toda una interfaz.'],['Elimina toda diferencia entre tiempo y dinero.','Una metáfora conserva semejanzas útiles aunque los dominios sigan siendo distintos.']]],
  [0,121,'En una interfaz web aparecen “navegar”, “visitar”, “página”, “mapa” y “ancla”. ¿Cómo los presenta el tema?',[
    ['Como vocabulario metafórico incorporado al lenguaje de la interacción.','La página 121 incluye esos términos entre los ejemplos cotidianos.'],['Como propiedades físicas obligatorias de Internet.','Son maneras familiares de conceptualizar acciones y elementos digitales.'],['Como errores que deben retirarse de cualquier web.','El tema los muestra como ejemplos, no como prohibiciones generales.'],['Como nombres exclusivos de componentes del hardware.','Describen conceptos de interacción, no piezas físicas del ordenador.']]],
  [0,122,'Al encontrarse por primera vez con una herramienta tecnológica, una persona intenta entenderla comparándola con algo conocido. ¿Qué proceso refleja?',[
    ['El uso espontáneo de una metáfora verbal para interpretar el nuevo dominio.','La página 122 señala esa tendencia a comparar la tecnología nueva con algo conocido.'],['La eliminación de todo modelo mental previo.','La persona está utilizando conocimiento previo, no descartándolo.'],['Una prueba de que ambos objetos son físicamente idénticos.','La comparación requiere alguna semejanza útil, no identidad total.'],['La creación automática de una metáfora global coherente.','Una comparación inicial no constituye necesariamente el marco de todo el sistema.']]],
  [0,123,'¿Qué se transfiere desde un dominio familiar a otro no familiar en el ejemplo del teclado?',[
    ['Conocimientos sobre sus elementos y sobre las relaciones entre ellos.','La página 123 destaca la transferencia tanto de elementos como de relaciones.'],['Únicamente la forma y el peso físico de cada objeto.','La transferencia es conceptual y no se limita a propiedades físicas.'],['El código fuente que implementa el dispositivo conocido.','El usuario traslada conocimiento, no la implementación informática.'],['Solo palabras aisladas, nunca relaciones de funcionamiento.','El tema menciona expresamente los elementos y sus relaciones.']]],
  [0,124,'¿Cuál es la ventaja principal de una metáfora verbal al comenzar a usar un sistema?',[
    ['Permite desarrollar más rápidamente conocimiento del dominio nuevo a partir del conocimiento previo.','Es la ventaja formulada en la página 124.'],['Garantiza que no habrá que aprender ninguna diferencia.','La página también advierte que existen limitaciones y diferencias.'],['Hace innecesaria toda realimentación de la interfaz.','La metáfora no sustituye la comunicación del resultado de las acciones.'],['Obliga a comprender la arquitectura interna antes de actuar.','Su propósito es facilitar el inicio desde algo ya familiar.']]],
  [0,124,'La tecla de retorno movía físicamente el carro de una máquina de escribir, pero en el ordenador desplaza el puntero a la línea siguiente. ¿Qué conclusión apoya?',[
    ['La metáfora tiene diferencias; al asimilarlas, el usuario construye un nuevo modelo mental.','La página 124 presenta este caso como límite y posterior aprendizaje.'],['La existencia de una diferencia invalida necesariamente toda metáfora.','El ejemplo sigue considerándose útil pese a no coincidir por completo.'],['El ordenador debe incorporar un carro físico para conservar la metáfora.','La correspondencia útil no exige copiar el mecanismo material.'],['La tecla funciona únicamente como una metáfora visual global.','El caso ilustra la transferencia verbal y funcional desde una herramienta conocida.']]],

  [1,126,'Un icono permite reconocer un objeto conocido y, por extensión, comprender para qué sirve un control. ¿Qué concepto describe?',[
    ['Una metáfora visual.','La página 126 la define como una imagen reconocible que permite comprender su propósito.'],['Una propiedad mágica de una carpeta.','No se está comparando una capacidad virtual con una limitación física.'],['Un análisis de requisitos.','El caso trata de representación y comprensión, no de enumerar funciones del sistema.'],['Una regla de memoria procedimental.','Aunque usarlo pueda aprenderse, la definición pedida es la de metáfora visual.']]],
  [1,126,'¿Qué amplitud puede tener una metáfora visual?',[
    ['Puede ir desde una imagen pequeña hasta una pantalla completa.','Ese intervalo aparece expresamente en la página 126.'],['Debe limitarse a iconos de 16 píxeles.','El tema no fija ese tamaño y admite pantallas completas.'],['Solo puede aparecer como texto sin imágenes.','Eso contradice su carácter visual.'],['Tiene que abarcar siempre todo el sistema.','Ese alcance corresponde a una posible metáfora global, no a toda metáfora visual.']]],
  [1,129,'Una persona comprende inmediatamente qué hace un icono sin elaborar conscientemente una cadena de razonamientos. ¿Cómo denomina el tema este fenómeno?',[
    ['Intuición: cognición inmediata sin utilizar inferencia o razonamiento.','Es la definición de intuición de la página 129.'],['Análisis de tareas: enumeración de acciones del usuario.','No se está descomponiendo una tarea.'],['Extensibilidad: capacidad de añadir funciones futuras.','La inmediatez de la comprensión no mide la extensión de la metáfora.'],['Memorización literal del código de la aplicación.','El caso describe reconocimiento y asociación, no conocimiento de la implementación.']]],
  [1,129,'¿Por qué puede entenderse intuitivamente una metáfora visual?',[
    ['Porque se conecta mentalmente con otros procesos aprendidos previamente.','La página 129 relaciona la comprensión con aprendizajes anteriores.'],['Porque toda imagen tiene un único significado universal.','Las interpretaciones pueden variar, especialmente entre culturas.'],['Porque elimina automáticamente todas las diferencias entre dominios.','La comparación puede conservar diferencias que después deben aprenderse.'],['Porque el usuario deduce el algoritmo interno línea por línea.','La intuición descrita no exige razonar sobre el código.']]],
  [1,130,'El diseñador entiende una imagen como “guardar”, pero la audiencia la interpreta como “enviar”. ¿Qué condición de la metáfora ha fallado?',[
    ['La asociación no es percibida de manera similar por diseñador y usuario.','La página 130 exige una base de asociación compartida.'],['La pantalla no contiene suficientes propiedades físicas como peso o ruido.','Esas propiedades no resolverían necesariamente la diferencia de interpretación.'],['La metáfora tiene obligatoriamente demasiado volumen estructural.','El caso demuestra una asociación divergente, no exceso de estructura.'],['El usuario ha identificado correctamente una metáfora global.','Las interpretaciones distintas indican lo contrario.']]],
  [1,130,'Se usa un objeto cotidiano de una región para una audiencia que nunca lo ha visto. ¿Qué riesgo predice el tema?',[
    ['La metáfora puede fallar por no compartir usuario y desarrollador la misma base cultural.','La página 130 advierte expresamente de este riesgo.'],['La metáfora se vuelve universal por ser visual.','Una imagen también depende del conocimiento cultural.'],['El objeto adquiere automáticamente el significado pretendido.','La familiaridad no puede darse por supuesta.'],['Solo se perjudica el rendimiento del hardware.','El problema afecta a la interpretación humana de la interfaz.']]],
  [1,131,'Una aplicación presenta todo su contenido como un museo y dentro usa salas, vitrinas y recorridos. ¿Qué papel cumple “museo”?',[
    ['Actúa como metáfora global que proporciona el marco para las demás.','La página 131 define así la metáfora global.'],['Es únicamente un verbo de acción.','Museo representa un lugar y aquí organiza el sistema entero.'],['Es una diferencia accidental sin efecto sobre el diseño.','El marco condiciona cómo se integran las metáforas subordinadas.'],['Es necesariamente una metáfora verbal sin representación visual.','El ejemplo describe un marco visual y conceptual de alcance global.']]],
  [1,131,'¿Qué requisito se establece para las metáforas incluidas dentro de una metáfora global?',[
    ['Deben integrarse adecuadamente en el marco global.','La coherencia de integración se señala en la página 131.'],['Deben contradecir el marco para llamar la atención.','La contradicción puede romper las expectativas creadas.'],['Deben proceder todas de dominios culturales incompatibles.','Eso dificultaría construir una interpretación coherente.'],['Deben eliminarse y dejar una única imagen sin acciones.','Una metáfora global sirve de marco a otras metáforas, no las impide.']]],
  [2,136,'¿Qué representa la metáfora del escritorio y qué relevancia histórica le atribuye el tema?',[ 
    ['Reproduce una oficina con sus objetos y fue la primera metáfora global.','La página 136 reúne ambas características.'],['Reproduce una fábrica y fue la primera metáfora exclusivamente auditiva.','No coincide ni el dominio representado ni el tipo de metáfora.'],['Representa la memoria humana y nunca se extendió.','El tema indica que está muy extendida.'],['Copia la arquitectura electrónica interna del ordenador.','Representa un entorno de oficina comprensible para el usuario.']]],
  [2,137,'¿Qué correspondencia entre carpetas reales y virtuales conserva la metáfora del escritorio?',[
    ['Ambas pueden contener documentos, abrirse, anidarse y moverse.','Son las correspondencias enumeradas en la página 137.'],['Ambas pesan lo mismo y producen idéntico ruido.','Peso y ruido son propiedades físicas ausentes en la versión virtual.'],['Solo las reales pueden contener algo.','La función de contenedor es la base compartida de la metáfora.'],['Solo las virtuales pueden abrirse o moverse.','Esas acciones existen en ambos dominios.']]],
  [2,137,'Una carpeta virtual no pesa ni hace ruido cuando se abre. ¿Cómo clasifica el tema estas diferencias?',[
    ['Como propiedades físicas del objeto real que están ausentes en el virtual.','La página 137 utiliza exactamente esos ejemplos.'],['Como propiedades mágicas añadidas por el sistema.','Las propiedades mágicas son capacidades nuevas, como ordenar automáticamente.'],['Como prueba de que no existe ninguna analogía útil.','La metáfora mantiene otras correspondencias funcionales.'],['Como requisitos que toda interfaz debe simular obligatoriamente.','El tema constata su ausencia, no exige reproducirlas.']]],
  [2,137,'Ordenar automáticamente carpetas por nombre o reproducir un conjunto completo son ejemplos de:',[
    ['Propiedades “mágicas” que la versión virtual añade al objeto metafórico.','Así denomina la página 137 a esas capacidades.'],['Propiedades físicas imprescindibles de una carpeta de cartón.','No son capacidades ordinarias del objeto real.'],['Errores que impiden extender cualquier metáfora.','El tema los presenta como ampliaciones del objeto virtual.'],['Metáforas verbales sin ninguna relación con el escritorio.','Son capacidades de objetos dentro de la metáfora del escritorio.']]],
  [2,138,'¿Por qué se combinó la metáfora del escritorio con otras metáforas?',[
    ['Para permitir que los usuarios realizaran un conjunto más amplio de tareas.','Esa es la finalidad indicada en la página 138.'],['Para reducir la interfaz únicamente a carpetas inmóviles.','La combinación amplía posibilidades en vez de restringirlas.'],['Para eliminar toda referencia a objetos conocidos.','Las metáforas añadidas también se apoyan en dominios familiares.'],['Para hacer que cada elemento perteneciera a un marco incompatible.','La composición debe seguir siendo comprensible dentro del sistema.']]],
  [2,138,'La barra de desplazamiento se relaciona históricamente con un papiro que se mueve para leer. ¿Qué metáfora compuesta es?',[
    ['La metáfora del rollo.','Es el ejemplo dado en la página 138.'],['La metáfora de la papelera.','La papelera representa depósito y eliminación o reciclaje.'],['La metáfora del funeral.','Ese es un ejemplo de comparación inadecuada.'],['La metáfora del reproductor de vídeo.','El tema la usa como asociación errónea para controlar una impresora.']]],
  [2,138,'¿De qué práctica familiar proceden las acciones de “cortar y pegar” integradas en el escritorio?',[
    ['Del diseño de páginas de una imprenta.','La página 138 atribuye a ese trabajo la metáfora.'],['Del movimiento de un rollo de papiro.','Ese origen corresponde a la barra de desplazamiento.'],['De la clasificación alfabética automática.','Esa es una capacidad añadida a las carpetas virtuales.'],['Del envío de cartas por correo.','Ese dominio inspira la metáfora del correo electrónico.']]],
  [2,139,'¿Qué significa que una metáfora haga “invisible” el ordenador?',[
    ['Que se vuelva transparente para el usuario y no le exija esfuerzo cognitivo consciente.','La página 139 formula así el objetivo final.'],['Que apague físicamente la pantalla durante la interacción.','Invisible se usa en sentido cognitivo, no óptico.'],['Que oculte las consecuencias de todas las acciones.','La falta de realimentación dificultaría comprender el sistema.'],['Que obligue a memorizar la implementación interna.','Eso aumentaría, en vez de reducir, el esfuerzo cognitivo.']]],

  [3,141,'Antes de escoger iconos o nombres, el equipo estudia qué hará el sistema y qué podrá hacer la persona. ¿En qué fase está?',[
    ['En la definición funcional, primera fase de la metodología.','Las páginas 141–142 sitúan ahí la comprensión de lo que se modelará.'],['En la extensión no intuitiva de la metáfora.','Todavía no se ha generado ni extendido ninguna metáfora.'],['En la elección de una asociación inadecuada.','Analizar funciones no constituye por sí mismo una asociación.'],['En la representación final de cada acción.','Eso llega después de comprender funciones, usuarios y alternativas.']]],
  [3,142,'¿Qué emparejamiento distingue correctamente los dos análisis de la definición funcional?',[
    ['Qué puede hacer el sistema: requisitos; qué puede hacer el usuario: tareas.','Es la distinción de la página 142.'],['Qué puede hacer el sistema: tareas; qué puede hacer el usuario: requisitos.','Intercambia ambos análisis.'],['Qué puede hacer el sistema: cultura; qué puede hacer el usuario: hardware.','No son las categorías indicadas en esta fase.'],['Qué puede hacer el sistema: intuición; qué puede hacer el usuario: extensibilidad.','Son conceptos relevantes en otros puntos, pero no esta distinción.']]],
  [3,143,'Para identificar los problemas de usuario, ¿qué actuación recomienda el tema?',[
    ['Analizar sus dificultades, observar funciones similares y probar la comprensión mediante prototipos.','La página 143 reúne esas tres actividades.'],['Preguntar solo al programador y no mostrar nada a usuarios.','La fase exige observar cómo entienden y utilizan la propuesta.'],['Elegir primero una metáfora y prohibir cualquier revisión.','La investigación de problemas debe informar la generación posterior.'],['Medir únicamente el tiempo de arranque del ordenador.','Ese dato no descubre cómo comprende el usuario la funcionalidad.']]],
  [3,144,'¿Qué fuente se examina para generar candidatas a metáfora?',[
    ['La manera tradicional de realizar las tareas en entornos como oficinas, fábricas o escuelas.','Es el examen propuesto en la página 144.'],['Solo la estructura del código fuente del nuevo sistema.','La metodología busca herramientas y prácticas familiares de los usuarios.'],['Exclusivamente metáforas ya descartadas por la audiencia.','Se investigan tareas, problemas y herramientas reales.'],['Únicamente objetos sin relación con las dificultades detectadas.','Las candidatas deben ayudar precisamente con lo difícil de comprender.']]],
  [3,144,'Tras observar las herramientas tradicionales, ¿cuáles son buenas candidatas a metáfora?',[
    ['Las que incorporan características relacionadas con aquello que al usuario le cuesta comprender.','Según la página 144, pueden hacer fácil lo que resulta difícil.'],['Las más vistosas aunque no guarden relación con la tarea.','La decoración no aporta por sí sola una analogía útil.'],['Las que exigen conocer previamente la implementación nueva.','La candidata debe apoyarse en conocimiento familiar.'],['Las que reproducen todos los inconvenientes del proceso tradicional.','Se busca facilitar la comprensión, no copiar indiscriminadamente.']]],
  [3,145,'Una candidata ofrece muchas relaciones útiles, evita expectativas falsas, se representa con claridad, la audiencia la entiende y admite ampliaciones. ¿Qué se está valorando?',[
    ['Su volumen estructural, aplicabilidad, representabilidad, adaptabilidad y extensibilidad.','Son los criterios de evaluación enumerados en la página 145.'],['Solo su parecido cromático con el objeto real.','La evaluación abarca más dimensiones que la apariencia.'],['Únicamente la velocidad del procesador.','Es una medida técnica ajena a los criterios citados.'],['La obligación de que toda metáfora sea exclusivamente sonora.','La metáfora ideal puede asociar representación visual, auditiva y palabras.']]],
  [3,146,'En la versión alternativa de la metodología, ¿qué debe hacerse después de relacionar información familiar y nueva?',[
    ['Estudiar el grado de ajuste: coincidencias y diferencias entre ambas.','Ese es el segundo punto de la página 146.'],['Suponer que toda relación inicial es válida.','La diapositiva advierte expresamente que no todas las comparaciones valen.'],['Eliminar las diferencias para afirmar que los dominios son idénticos.','Evaluarlas es necesario para prever límites y errores.'],['Representar primero el código interno del sistema.','La versión se centra en el tipo de comparación y su ajuste.']]],
  [3,147,'¿Qué clasificación de los dos errores coincide con las páginas 147–148?',[
    ['Controlar una impresora como un vídeo es una asociación inadecuada; expulsar un disquete arrastrándolo a la papelera es una extensión no intuitiva.','Cada caso corresponde al rótulo de su diapositiva.'],['Ambos son ejemplos de una definición funcional completa.','Son fallos de la metáfora, no análisis previos de funciones.'],['El reproductor es una propiedad física ausente y el disquete una metáfora global.','Esas categorías no describen los problemas mostrados.'],['Ambos demuestran que cualquier metáfora conocida es necesariamente correcta.','Los ejemplos se incluyen precisamente para mostrar errores posibles.']]],

  [4,150,'¿Qué correspondencias propone el tema para diseñar metáforas efectivas?',[
    ['Asociar clases y atributos a objetos familiares, y procesos y algoritmos a verbos de acción.','La página 150 distingue esas dos vías de asociación.'],['Asociar objetos solo a sonidos y acciones solo a colores.','Esa restricción no aparece en el método.'],['Asociar toda función a un lugar sin utilizar objetos ni actividades.','El tema admite metáforas de objetos, actividades y lugares.'],['Asociar el código fuente a palabras elegidas al azar.','La asociación debe apoyarse en conocimiento familiar y relaciones comprensibles.']]],
  [4,150,'¿Qué clasificación es correcta según los tipos de metáforas del tema?',[
    ['Libro es de objeto, viaje es de actividad y museo es de lugar.','Coincide con los ejemplos de la página 150.'],['Libro es de actividad, viaje es de lugar y museo es de objeto.','Intercambia las tres categorías.'],['Libro, viaje y museo son exclusivamente propiedades mágicas.','Son dominios candidatos de objeto, actividad y lugar.'],['Ninguno puede utilizarse como metáfora de interfaz.','Los tres aparecen expresamente como ejemplos.']]],
  [4,152,'¿Qué secuencia sigue el ejercicio de diseño de una biblioteca de imágenes digitales?',[
    ['Escoger objetos, representarlos visualmente, elegir verbos de acción y representar visualmente las acciones.','Es la secuencia de cuatro pasos de las páginas 152–156.'],['Elegir colores al azar, programar, omitir acciones y preguntar al final.','No corresponde a la metodología presentada.'],['Representar acciones, borrar los objetos y después definir requisitos.','Invierte y elimina pasos esenciales del ejercicio.'],['Escoger únicamente verbos sin identificar los objetos implicados.','El ejercicio comienza por estantería, álbum, hoja y foto.']]],
  [4,155,'En el ejercicio de la biblioteca, ¿qué conjunto contiene únicamente verbos elegidos para las acciones?',[
    ['Crear o añadir, borrar, seleccionar y mover.','Son las acciones enumeradas en la página 155.'],['Estantería, álbum, hoja y foto.','Esos son los objetos escogidos en el primer paso.'],['Casa, plaza, museo y ciudad.','Son ejemplos de lugares de la página 150.'],['Peso, ruido, tamaño y material.','No es la lista de acciones del ejercicio.']]],
  [4,158,'¿Por qué la papelera funciona como metáfora y qué capacidad adicional se asocia a ella?',[
    ['Es habitual en muchas culturas, recibe elementos que ya no sirven y permite recuperarlos o reciclarlos.','La página 158 combina familiaridad, depósito y reciclaje.'],['Es desconocida para la mayoría y destruye siempre de inmediato.','Contradice la familiaridad y la posibilidad de reciclaje indicadas.'],['Representa exclusivamente el envío de información a distancia.','Esa función se asocia a la metáfora del correo.'],['Sirve para seleccionar una zona de un dibujo con precisión.','Esa no es la función atribuida a la papelera.']]],
  [4,159,'¿Qué parte de la metáfora de las tijeras resulta menos intuitiva y debe aprenderse?',[
    ['Su relación con el portapapeles.','La página 159 dice expresamente que ese enlace debe aprenderse.'],['La idea básica de cortar una parte de un documento o dibujo.','Esa función procede directamente del uso familiar de las tijeras.'],['La posibilidad física de cortar papel o tela.','Ese conocimiento familiar sostiene la metáfora.'],['Su clasificación como metáfora de lugar.','Las tijeras son un objeto, no un lugar.']]],
  [4,160,'Un bote inclinado vierte pintura sobre una figura. ¿Qué operación pretende comunicar?',[
    ['Llenar el interior de un objeto con un color determinado.','Es la interpretación descrita en la página 160.'],['Mover el objeto a otra carpeta.','La imagen de pintura no comunica esa acción.'],['Enviar el objeto por correo electrónico.','El correo utiliza otro dominio metafórico.'],['Ordenar alfabéticamente todas las carpetas.','Esa es una capacidad virtual distinta.']]],
  [4,161,'¿Por qué califica el tema al portapapeles como una metáfora pobre aunque sea fácil de intuir?',[
    ['Porque no recoge más de una cosa, no muestra de dónde vienen los documentos y carece de historial.','Son las limitaciones enumeradas en la página 161.'],['Porque no permite pasar información entre aplicaciones.','Precisamente pretende representar ese componente del sistema operativo.'],['Porque representa perfectamente todas las capacidades del sistema.','El problema es que deja aspectos sin cubrir que deben aprenderse.'],['Porque ninguna persona reconoce un portapapeles como objeto.','La crítica se dirige a su cobertura funcional, no a una incomprensión absoluta.']]]
].map((q,i)=>({id:i+1,bloque:q[0],pagina:q[1],enunciado:q[2],opciones:q[3].map((o,j)=>({texto:o[0],explicacion:o[1],correcta:j===0}))}));
